name: Build & Trigger Render Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run lint (optional)
        run: echo "No linter configured"

      - name: Build (noop)
        run: echo "No build step required for this simple app"

      - name: Trigger Render deploy
        if: ${{ secrets.RENDER_API_KEY && secrets.RENDER_SERVICE_ID }}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering deploy for Render service $RENDER_SERVICE_ID"
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -d '{"clearCache":true}'

      - name: Notify if secrets missing
        if: ${{ !secrets.RENDER_API_KEY || !secrets.RENDER_SERVICE_ID }}
        run: echo "RENDER_API_KEY or RENDER_SERVICE_ID is not set — set them in repository secrets to enable automatic deploys."
